
RA_output = {'retrieval_status': 'success', 
'discovered_agency': 'Department for Registration of Persons', 
'source_url': 'https://drp.gov.lk/en/normal.php', 
'pdf_urls': ['https://drp.gov.lk/en/assets/formats/application.pdf', 'https://drp.gov.lk/en/assets/downloads/application%2002_3english.pdf'], 
'form_pdfs': ['https://www.rgd.gov.lk/web/images/application_forms/birth/Particulars_for_registration_of_a_birth_2017-04-25.pdf','https://drp.gov.lk/en/assets/formats/application.pdf', 'https://drp.gov.lk/en/assets/downloads/application%2002_3english.pdf'], 
'manual_pdfs': [], 
'regulations': [{'content': 'Basic requirements to be met to apply for a National Identity Card. Every person who is a citizen of Sri Lanka and who has attained or attains the age of 15 years shall apply for a National Identity card. Submitting an application requires forwarding the application through the relevant certifying officer (School Principal/Parivenadhipathi, Grama Niladhari, Estate Superintendent). Fees are payable through the certifying officer. Documents to be submitted: Duly completed application (Form D.R.P/1,7,8), Birth certificate or extract of the birth registry certified by the Additional District Registrar, ICAO standard photograph obtained within 06 month period, Receipt of payment of application fee. Issuance of National Identity Cards under Normal Service is by post after forwarding to the department.', 
'source': 'https://drp.gov.lk/en/normal.php'}], 
'required_documents': [{'doc_id': 'application_form', 
'doc_name': 'Duly completed application (Form D.R.P/1,7,8)', 'doc_name_si': '', 'doc_name_ta': '', 
'mandatory': True, 'format': 'original', 'notes': ''}, 
{'doc_id': 'birth_certificate', 
'doc_name': 'Birth certificate or extract of the birth registry certified by the Additional District Registrar', 'doc_name_si': '', 'doc_name_ta': '', 'mandatory': True, 'format': 'original', 'notes': ''}, 
{'doc_id': 'photograph', 'doc_name': 'ICAO standard photograph obtained within 06 month period', 'doc_name_si': '', 'doc_name_ta': '', 'mandatory': True, 'format': 'original', 'notes': ''}, 
{'doc_id': 'payment_receipt', 'doc_name': 'Receipt of payment of application fee', 'doc_name_si': '', 'doc_name_ta': '', 'mandatory': True, 'format': 'original', 'notes': ''}],
 'fees': {'amount': 'LKR 0', 'currency': 'LKR', 'payment_methods': ['Through certifying officer (School Principal, Grama Niladhari, Estate Superintendent)'], 
'notes': 'No fee is listed for first-time issuance; fees apply for revised, duplicate, one‑day service, translation, verification, and fines.'}, 
'processing_time': '', 'data_source': 'live_web', 'notes': ''}